### ISSUE TITLE
Splitting actions

### ISSUE THREAD

**Issue by strogonoff** [paneron/dataset-build-action#2]
Per @CAMOBAP’s suggestion, we’ll split the action into at least two:

* Action responsible for dataset build
* Action responsible for deployment

This will provide better separation of concerns, and would allow different data repositories to use different deployment mechanisms.

Both actions will live in the same repository.

**Comment by CAMOBAP** [comment]
Already done we have separated `build` and `aws-deploy` actions both available in this repo
