### ISSUE TITLE
How to pass scaffolding repository URL?

### ISSUE THREAD

**Issue by strogonoff** [paneron/dataset-build-action#7]
For example, let’s look at https://github.com/paneron/iev-data-subset/blob/feature/migrate-to-gha/.github/workflows/deploy-master.yaml#L14.

That site should be built using https://github.com/paneron/glossary-site-scaffolding. However, where is that specified?

The idea is that the action should support a configuration option that would tell it which scaffolding template to use. The option can simply accept a URL to any Git repository with scaffolding, and use that URL to fetch scaffolding project code.

**Comment by CAMOBAP** [comment]
this configured in `scaffolding` input here https://github.com/paneron/dataset-build-action/blob/feature/first-release/build/action.yml#L4-L7

And default values is `paneron/glossary-site-scaffolding`

An explicit example is:
```
...
- uses: paneron/dataset-build-action/build@main
   with:
      scaffolding: paneron/glossary-site-scaffolding
...
```

At this point it expects only GitHub repos, but I can extend it if need

**Comment by strogonoff** [comment]
Got it.

**Comment by strogonoff** [comment]
I don't think it should have a default, it should fail with error if no scaffolding repo is given, since it’s the key setting

**Comment by CAMOBAP** [comment]
@strogonoff agree, I will fix this

**Comment by strogonoff** [comment]
Filed https://github.com/paneron/dataset-build-action/issues/8
